["Среда"]

[["Среда.lesson"]]
time = "08:10-9:40"
subject = "Английский язык A1"
type = "Практика"
teacher = "Яковлева Ольга Александровна"
audience = "3110"
adress = "ул.Ломоносова, д.9, лит. Е"

[["Среда.lesson"]]
time = "09:50-11:20"
subject = "Английский язык A1"
type = "Практика"
teacher = "Яковлева Ольга Александровна"
audience = "3110"
adress = "ул.Ломоносова, д.9, лит. Е"

[["Среда.lesson"]]
time = "13:30-15:00"
subject = "Программирование"
type = "Лекция"
teacher = "Гаврилов Антон Валерьевич"
audience = "Актовый зал(1216/0(усл))"
adress = "ул.Ломоносова, д.9, лит. M"

["Суббота"]

[["Суббота.lesson"]]
time = "09:50-11:20"
subject = "Программирование"
type = "Лабораторная"
teacher = "Выдра Андрей Михайлович"
audience = "1320"
adress = "Кронверкский пр., д.49, лит.А"

[["Суббота.lesson"]]
time = "11:30-13:00"
subject = "Программирование"
type = "Лабораторная"
teacher = "Выдра Андрей Михайлович"
audience = "1320"
adress = "Кронверкский пр., д.49, лит.А"